export const en = {
  geo: "Georgian",
  en: "English",
  loginHeader1: "Sign in to your Account",
  loginHeader2: "Don’t have an account?",
  registerHeader1: "Get Started now",
  registerHeader2: "Log in to explore about our app",
  signIn: "Sign In",
  signUp: "Sign Up",
  login: "Login",
  userName: "Username",
  fullName: "Fullname",
  mail: "Email",
  password: "Password",
  repeatPassword: "Repeat the password",
  enter: "Enter",
  remember: "Remember me",
  forgortPass: "Forgot Password ?",
  or: "Or",
};

export const geo = {
  geo: "ქართული",
  en: "ინგლისური",
  loginHeader1: "გაიარე ავტორიზაცია",
  loginHeader2: "არ გაქვს ანგარიში?",
  registerHeader1: "დაიწყე ახლავე",
  registerHeader2: "გაიარეთ ავტორიზაცია",
  signIn: "ავტორიზაცია",
  signUp: "რეგისტრაცია",
  login: "ლოგინი",
  password: "პაროლი",
  fullName: "სახელი და გვარი",
  mail: "Email",
  userName: "მომხმარებლის სახელი",
  repeatPassword: "გაიმეორე პაროლი",
  enter: "შეიყვანეთ",
  remember: "დამახსოვრება",
  forgortPass: "დაგავიწყდა პაროლი ?",
  or: "ან",
};
